#!/bin/sh

if [ "$1" = "status" ]
then

	if [ -z "$(nmcli con show --active)" ] || ! ping 8.8.8.8 -c 1 >/dev/null 2>&1
	then
		exit 1
	fi
elif [ "$1" = "vpn" ]
then
	if ! nmcli con show --active | grep -q vpn
	then
		exit 1
	fi
fi
