#!/bin/sh

playerctl -p "$PLAYER" -F metadata -f '{{artist}} - {{title}}' | while read -r music
do
    if [ "$music" = '' ]
    then
        eww update player-opened=false
    else
        if [ "$(eww get player-opened)" = false ]
        then
            sleep 1

            music="$(playerctl -p "$PLAYER" metadata -f '{{artist}} - {{title}}')"
        fi

        eww update player-opened=true
        eww update "player-music=$music"
    fi
done
